### ISSUE TITLE
How to view history of deleted file?

### ISSUE THREAD

**Issue by steel3d** [JonathanAquino/git-time-lapse-view#7]
I have a file that I moved from one repo to another. This means it's been deleted from the first repo. Is there any way to look at the history of such a file? Simply typing in the old path doesn't seem to work.

Amazing tool, by the way! Thanks so much!

**Comment by jgscherber** [comment]
If you know the commit SHA where the file was deleted, you can checkout the repo at the commit right before (when the file still existed) and then load the file's path using the git-time-lapse-view tool

**Comment by steel3d** [comment]
That works. Thanks!
